### ISSUE TITLE
Bug fixes for new changes

### ISSUE THREAD

**Issue by alesanchezr** [miamiworks/web#94]
Ok so the las changes made where:
- Added algolia search
- removed events from the website
- Jobs search bar layout
- Other small UI fixes.

But there are some bugs:

<img width="556" alt="Screen Shot 2021-01-05 at 2 46 33 PM" src="https://user-images.githubusercontent.com/426452/103692076-4140f780-4f65-11eb-99a2-a1b535694675.png">
<img width="546" alt="Screen Shot 2021-01-05 at 2 47 00 PM" src="https://user-images.githubusercontent.com/426452/103692085-43a35180-4f65-11eb-9299-892d0ae33891.png">

**Comment by alesanchezr** [comment]
@jferragut

**Comment by jferragut** [comment]
**Tasks:**
- [ ] Learn Key skills is not loading
- [ ] Remove events from Navbar
- [ ] Courses not loading on jobs page
- [ ] Job search doesn't work when pressing enter (need key press event)
- [ ] Remove indexing via description from Algolia search

**Comment by jferragut** [comment]
Courses show on jobs locally and on prod
<img width="1628" alt="Screen Shot 2021-01-10 at 4 24 40 PM" src="https://user-images.githubusercontent.com/31458614/104135834-67e5a080-5360-11eb-980b-28ecb4b73948.png">

**Comment by jferragut** [comment]
@berno0 sent you a message about this on slack but the algolia is over quota so I cannot test the search. 
<img width="712" alt="Screen Shot 2021-01-10 at 4 50 45 PM" src="https://user-images.githubusercontent.com/31458614/104136435-09babc80-5364-11eb-8eaa-365f59004b52.png">

I am also working with @alesanchezr to add me to Algolia so I can update the indexing for the final item on the task list.

**Comment by jferragut** [comment]
Cannot update the indices 
<img width="553" alt="Screen Shot 2021-01-10 at 4 54 27 PM" src="https://user-images.githubusercontent.com/31458614/104136495-9796a780-5364-11eb-8175-1491345b3efe.png">

**Comment by jferragut** [comment]
@berno0 so to clarify the final task, the indexing on algolia should exclude the description? Are there any other fields we should exclude?

**Comment by berno0** [comment]
@jferragut  yes the indexing should not include the description since we are currently not displaying the description.

**Comment by jferragut** [comment]
@berno0 never got feedback on these 2 items:
- Learn Key skills is not loading Tested locally and this shows up.
- Courses not loading on jobs page Tested locally and this shows up as well.
I need you to paste a screenshot here of what you are seeing.

**Comment by berno0** [comment]
@jferragut  Cant replicate the issue anymore in the dev deployment. I will keep an eye on this. Thanks!
